# Generated by Django 5.0.6 on 2024-07-24 07:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(max_length=11, unique=True)),
                ('special_req', models.BooleanField(default=False)),
                ('special_reg', models.BooleanField(default=False)),
                ('counts', models.IntegerField(default=0)),
                ('last_call', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
